import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { useCart } from "../lib/cart";
const money=(c:number)=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(c/100);
export function CheckoutPage(){
 const {items,subtotalCents,clear}=useCart();const [session,setSession]=useState<boolean|null>(null);const [notes,setNotes]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(!!data.session))},[]);
 if(!items.length)return <main className="page text-center"><h1 className="text-4xl font-black">YOUR CART IS EMPTY.</h1><Link to="/shop" className="mt-6 inline-block underline font-bold">Back to shop</Link></main>;
 if(session===null)return <main className="page">Checking account…</main>;
 if(!session)return <main className="page text-center"><p className="eyebrow">Secure checkout</p><h1 className="mt-3 text-5xl font-black">SIGN IN TO CONTINUE.</h1><p className="mt-5 text-zinc-500">Your cart stays here while you sign in.</p><Link to="/account?next=/checkout" className="mt-8 inline-flex pill-dark">SIGN IN</Link></main>;
 async function pay(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error("Please sign in again.");let {data:cart}=await supabase.from("carts").select("id").eq("user_id",u.user.id).eq("status","ACTIVE").maybeSingle();let cartId=cart?.id;if(!cartId){const r=await supabase.from("carts").insert({user_id:u.user.id,currency:"ZAR"}).select("id").single();if(r.error)throw r.error;cartId=r.data.id}else{const r=await supabase.from("cart_items").delete().eq("cart_id",cartId);if(r.error)throw r.error}
 const ids=items.map(x=>x.variantId);const p=await supabase.from("public_catalogue").select("variant_id,price_cents").in("variant_id",ids);if(p.error)throw p.error;const priceMap=new Map((p.data??[]).map(x=>[x.variant_id,x.price_cents]));const rows=items.map(x=>({cart_id:cartId!,product_variant_id:x.variantId,quantity:x.quantity,unit_price_cents:priceMap.get(x.variantId)??0,currency:"ZAR",configuration:x.configuration??{},branding_notes:x.brandingNotes??null}));const ir=await supabase.from("cart_items").insert(rows);if(ir.error)throw ir.error;
 const {data:checkout,error:fnError}=await supabase.functions.invoke("create-yoco-checkout",{body:{cart_id:cartId,customer_notes:notes,shipping_method_slug:"collection"}});if(fnError)throw fnError;if(!checkout?.redirect_url)throw new Error("Payment checkout is not available yet. Yoco production configuration may still be pending.");clear();window.location.assign(checkout.redirect_url);
 }catch(e){setError(e instanceof Error?e.message:"Checkout failed.");setBusy(false)}}
 return <main className="page"><p className="eyebrow">Checkout</p><h1 className="mt-3 text-5xl font-black">READY TO GO.</h1><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_360px]"><form onSubmit={pay} className="card p-7"><label className="text-sm font-bold">Order notes</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Branding, timing, special requirements…" className="field mt-2 min-h-36"/>{error&&<p className="notice-error mt-4">{error}</p>}<button disabled={busy} className="mt-6 w-full pill-dark">{busy?"PREPARING SECURE PAYMENT…":"CONTINUE TO YOCO"}</button><p className="mt-4 text-xs leading-5 text-zinc-400">Collection is the currently active checkout method. The server recalculates the final order before payment.</p></form><aside className="card h-fit p-7"><p className="eyebrow">Summary</p>{items.map(i=><div key={i.variantId} className="mt-4 flex justify-between gap-3 text-sm"><span>{i.variantName} × {i.quantity}</span><strong>{i.priceCents===null?"Quote":money(i.priceCents*i.quantity)}</strong></div>)}<div className="mt-6 flex justify-between border-t border-black/10 pt-5"><span>Catalogue subtotal</span><strong>{money(subtotalCents)}</strong></div></aside></div></main>;
}
