import { Link } from "react-router-dom";

const useCases = [["Markets", "market", "Stand out in the crowd."], ["Events", "events", "Own the room."], ["Sports & outdoor", "sports", "Show up together."], ["Corporate", "corporate", "Make the launch count."], ["Roadshows", "roadshows", "Take your brand further."], ["Retail", "retail", "Be impossible to miss."]];
const principles = [["01", "Get noticed", "High-impact structures and displays that make your brand the first thing people see."], ["02", "Build your setup", "Start with one product or configure a complete presence around the way you show up."], ["03", "Make it yours", "Your brand, your colours, your space. Add the finishing details that make it unmistakably yours."], ["04", "Show up professionally", "Reliable, considered equipment for the moments where your brand has to perform."]];

export function HomePage() {
  return <main>
    <section className="hero-section"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow inverse">Outdoor branding • Events • Activations</p><h1>MAKE YOUR BRAND <em>IMPOSSIBLE</em> TO MISS.</h1><p className="hero-lede">Professional branded gazebos, flags, banners, furniture and promotional displays built to put your brand in the spotlight.</p><div className="hero-actions"><Link to="/shop" className="button button-gold">Shop products <span>↗</span></Link><Link to="/build-your-setup" className="button button-outline">Build your setup <span>↗</span></Link></div><div className="hero-proof"><span className="proof-line" /><span>From first impression<br />to full activation.</span></div></div><div className="hero-visual" aria-label="Abstract branded outdoor setup illustration"><div className="visual-glow" /><div className="tent-roof"><span>PRINT<br />KINGS</span></div><div className="tent-leg left" /><div className="tent-leg right" /><div className="banner-flag"><span>PK</span></div><div className="visual-caption"><span>01 / 04</span><strong>BRAND<br />THE SPACE.</strong></div></div></div><div className="hero-scroll"><span>Scroll to explore</span><span className="scroll-line" /></div></section>
    <section className="intro-section section-pad"><div className="intro-kicker"><span>01</span><span>The Print Kings system</span></div><div className="intro-content"><h2>BE SEEN.<br /><span>BE REMEMBERED.</span></h2><div><p className="section-lede">The right outdoor setup turns a blank space into a brand experience. Print Kings gives you the products, guidance and confidence to make that happen.</p><Link to="/solutions" className="text-link">Explore solutions <span>↗</span></Link></div></div></section>
    <section className="story-section section-pad"><div className="story-aside"><p className="eyebrow">A better way to show up</p><h2>FROM <span>BLANK SPACE</span><br />TO BRAND PRESENCE.</h2></div><div className="principles">{principles.map(([number, title, copy]) => <article className="principle" key={number}><span className="principle-number">{number}</span><div><h3>{title}</h3><p>{copy}</p></div><span className="principle-arrow">↗</span></article>)}</div></section>
    <section className="category-section section-pad"><div className="section-heading"><div><p className="eyebrow">02 / Choose your direction</p><h2>WHAT ARE YOU<br /><span>BUILDING?</span></h2></div><Link to="/shop" className="text-link">See all products <span>↗</span></Link></div><div className="category-grid">{useCases.map(([name, slug, copy], index) => <Link key={slug} to={`/build-your-setup?type=${slug}`} className={`category-tile tile-${index + 1}`}><span className="tile-index">0{index + 1}</span><div><h3>{name}</h3><p>{copy}</p></div><span className="tile-arrow">↗</span></Link>)}</div></section>
    <section className="setup-banner"><div><p className="eyebrow inverse">03 / Your next move</p><h2>BUILD THE<br /><em>COMPLETE SETUP.</em></h2><p>Choose a base, add your products, make it yours. Our guided builder helps you get to the right setup faster.</p><Link to="/build-your-setup" className="button button-gold">Start building <span>↗</span></Link></div><div className="setup-mark"><span>PK</span><small>BUILT<br />FOR<br />IMPACT</small></div></section>
    <section className="conversion-section section-pad"><div className="conversion-card"><p className="eyebrow">Ready when you are</p><h2>LET'S MAKE<br /><span>YOUR BRAND LOUDER.</span></h2><p>Tell us what you're building and we'll help you bring the right setup together.</p><div className="hero-actions"><Link to="/quote" className="button button-dark">Request a quote <span>↗</span></Link><Link to="/shop" className="text-link">Shop the catalogue <span>↗</span></Link></div></div></section>
  </main>;
}
