import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { supabase } from "../lib/supabase";
import type { Tables } from "../lib/database.types";
import { catalogueToCart, useCart } from "../lib/cart";
type Item=Tables<"public_catalogue">; type Image={id:string;external_url:string|null;storage_path:string|null;alt_text:string|null;is_primary:boolean;sort_order:number};
const money=(c:number|null)=>c===null?"Quote":new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(c/100);
export function ProductPage(){
 const {categorySlug,variantSlug}=useParams();const {add}=useCart();const [item,setItem]=useState<Item|null>(null);const [images,setImages]=useState<Image[]>([]);const [related,setRelated]=useState<Item[]>([]);const [qty,setQty]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let alive=true;(async()=>{if(!variantSlug)return;const {data,error}=await supabase.from("public_catalogue").select("*").eq("category_active",true).eq("variant_slug",variantSlug).maybeSingle();if(!alive)return;if(error){setError(error.message);setLoading(false);return}if(!data){setError("Product not found.");setLoading(false);return}setItem(data);const [{data:imgs},{data:rel}]=await Promise.all([supabase.from("product_images").select("id,external_url,storage_path,alt_text,is_primary,sort_order").eq("variant_id",data.variant_id).eq("approved",true).order("sort_order"),supabase.from("public_catalogue").select("*").eq("category_active",true).eq("category_slug",data.category_slug??categorySlug??"").neq("variant_id",data.variant_id).limit(4)]);if(alive){setImages(imgs??[]);setRelated(rel??[]);setLoading(false)}})();return()=>{alive=false}},[categorySlug,variantSlug]);
 const imageUrl=(x:Image)=>x.external_url??(x.storage_path?supabase.storage.from("product-images").getPublicUrl(x.storage_path).data.publicUrl:"");
 if(loading)return <main className="page"><p>Loading product…</p></main>;if(error||!item)return <main className="page"><p className="notice-error">{error||"Product not found."}</p><Link to="/shop" className="mt-6 inline-block font-bold underline">Back to shop</Link></main>;
 return <main className="page"><Link to={"/shop?category="+item.category_slug} className="text-sm font-bold text-zinc-500">← {item.category_name}</Link><div className="mt-8 grid gap-10 lg:grid-cols-2">
 <div className="rounded-[2rem] border border-black/10 bg-zinc-50 p-5">{images.length?<div className="grid gap-3">{images.slice(0,4).map(x=><img key={x.id} src={imageUrl(x)} alt={x.alt_text??item.variant_name??item.product_name??"Print Kings product"} className="max-h-[620px] w-full rounded-2xl object-contain"/>)}</div>:<div className="flex min-h-[480px] items-center justify-center rounded-2xl bg-zinc-100 text-center text-xs font-black uppercase tracking-widest text-zinc-400">Approved product imagery<br/>will appear here</div>}</div>
 <div><p className="eyebrow">{item.category_name}</p><h1 className="mt-3 text-5xl font-black tracking-tight">{item.variant_name??item.product_name}</h1>{item.variant_name&&item.product_name!==item.variant_name&&<p className="mt-2 text-lg text-zinc-500">{item.product_name}</p>}<p className="mt-7 text-3xl font-black">{money(item.price_cents)}</p><p className="mt-2 text-sm text-zinc-500">{item.short_description}</p>
 <div className="mt-8 border-y border-black/10 py-7"><h2 className="font-black">WHAT YOU GET</h2><p className="mt-3 leading-7 text-zinc-600">{item.description??"Professional Print Kings equipment configured for branded use."}</p><div className="mt-5 flex items-center gap-3"><button className="qty" onClick={()=>setQty(Math.max(1,qty-1))}>−</button><span className="w-8 text-center font-bold">{qty}</span><button className="qty" onClick={()=>setQty(qty+1)}>+</button></div><button onClick={()=>add(catalogueToCart(item),qty)} className="mt-5 w-full pill-dark">ADD TO CART</button><Link to="/quote" className="mt-3 block w-full pill-light text-center">REQUEST A QUOTE</Link></div>
 <div><h2 className="font-black">BRANDING</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{item.branding_supported?"Branding supported — final artwork requirements are confirmed during the order process.":"Branding availability is configuration-dependent; request a quote for confirmation."}</p></div></div></div>
 {related.length>0&&<section className="mt-20"><p className="eyebrow">More from {item.category_name}</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{related.map(x=><Link key={x.variant_id} to={"/shop/"+x.category_slug+"/"+x.variant_slug} className="card p-5"><p className="text-xs font-bold text-zinc-400">{x.category_name}</p><h3 className="mt-2 font-black">{x.variant_name??x.product_name}</h3><p className="mt-5 font-black">{money(x.price_cents)}</p></Link>)}</div></section>}</main>;
}
