import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { useCart } from "../lib/cart";
import type { Json } from "../lib/database.types";
export function QuotePage(){
 const {items,subtotalCents}=useCart();const [session,setSession]=useState<boolean|null>(null);const [name,setName]=useState("");const [company,setCompany]=useState("");const [phone,setPhone]=useState("");const [email,setEmail]=useState("");const [notes,setNotes]=useState("");const [busy,setBusy]=useState(false);const [success,setSuccess]=useState("");const [error,setError]=useState("");
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(!!data.session);if(data.session?.user.email)setEmail(data.session.user.email)})},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error("Please sign in to submit a quote.");const customerNotes=["Contact: "+name,"Company: "+company,"Phone: "+phone,"Email: "+email,notes].filter(Boolean).join("\n");const {data:quoteNumber,error:numberError}=await supabase.rpc("next_quote_number");if(numberError||!quoteNumber)throw numberError??new Error("Quote number could not be generated.");const {data:q,error:qerr}=await supabase.from("quotes").insert({quote_number:quoteNumber,user_id:u.user.id,status:"DRAFT",currency:"ZAR",subtotal_cents:subtotalCents,tax_cents:0,total_cents:subtotalCents,customer_notes:customerNotes}).select("id,quote_number").single();if(qerr)throw qerr;if(!q)throw new Error("Quote could not be created.");if(items.length){const rows=items.map(x=>({quote_id:q.id,product_variant_id:x.variantId,description:x.variantName,quantity:x.quantity,unit_price_cents:x.priceCents??0,tax_cents:0,total_cents:(x.priceCents??0)*x.quantity,configuration:(x.configuration??{}) as Json}));const {error:ierr}=await supabase.from("quote_items").insert(rows);if(ierr)throw ierr}setSuccess(q.quote_number);}catch(e){setError(e instanceof Error?e.message:"Quote submission failed.")}finally{setBusy(false)}}
 if(session===null)return <main className="page">Checking account…</main>;if(!session)return <main className="page text-center"><p className="eyebrow">Assisted sales</p><h1 className="mt-3 text-5xl font-black">GET A QUOTE.</h1><p className="mt-5 text-zinc-500">Sign in first so your quote can be securely linked to you.</p><Link to="/account?next=/quote" className="mt-8 inline-flex pill-dark">SIGN IN TO REQUEST A QUOTE</Link></main>;
 if(success)return <main className="page max-w-3xl"><p className="eyebrow">Quote received</p><h1 className="mt-3 text-5xl font-black">WE'VE GOT IT.</h1><p className="mt-5 text-lg leading-8 text-zinc-500">Your request <strong>{success}</strong> has been recorded. Print Kings can now review it.</p><Link to="/shop" className="mt-8 inline-flex pill-dark">CONTINUE SHOPPING</Link></main>;
 return <main className="page max-w-3xl"><p className="eyebrow">Assisted sales</p><h1 className="mt-3 text-5xl font-black">GET A QUOTE.</h1><p className="mt-5 text-lg leading-8 text-zinc-500">For bulk, custom, large-format or complete branded setups, tell us what you need.</p><form onSubmit={submit} className="mt-10 grid gap-4"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" className="field"/><input required value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email address" className="field"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company / organisation" className="field"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number" className="field"/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Requirements, branding, timing, quantities or anything else…" className="field min-h-40"/>{items.length>0&&<div className="card p-5"><p className="eyebrow">Cart attached</p><p className="mt-2 font-bold">{items.length} product line(s) · {new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(subtotalCents/100)} current catalogue value</p></div>}{error&&<p className="notice-error">{error}</p>}<button disabled={busy} className="pill-dark">{busy?"SUBMITTING…":"REQUEST QUOTE"}</button></form></main>;
}
